# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "kitchencenter-checkout"
client_id = "74adc42647b5bceb22e257adc6b385fb"
application_url = "https://innocent-along-decorative-killing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://innocent-along-decorative-killing.trycloudflare.com/auth/callback",
  "https://innocent-along-decorative-killing.trycloudflare.com/auth/shopify/callback",
  "https://innocent-along-decorative-killing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kitchencentercustomcehckout.myshopify.com"
